/* THIS FILE IS AUTOMATICALLY GENERATED! */
public static class GameTag { 

    public const string Untagged = "Untagged";
    public const string Respawn = "Respawn";
    public const string Finish = "Finish";
    public const string EditorOnly = "EditorOnly";
    public const string MainCamera = "MainCamera";
    public const string Player = "Player";
    public const string GameController = "GameController";
    public const string Ground = "Ground";
    public const string MovementPlaceholder = "MovementPlaceholder";
    public const string WorldCanvas = "WorldCanvas";
 }

public static class GameLayer { 

    public const int Default = 0;
    public const int DefaultMask = 1 << 0;
    public const int TransparentFX = 1;
    public const int TransparentFXMask = 1 << 1;
    public const int IgnoreRaycast = 2;
    public const int IgnoreRaycastMask = 1 << 2;
    public const int Water = 4;
    public const int WaterMask = 1 << 4;
    public const int UI = 5;
    public const int UIMask = 1 << 5;
    public const int Ground = 8;
    public const int GroundMask = 1 << 8;
    public const int StaticGeometry = 9;
    public const int StaticGeometryMask = 1 << 9;
    public const int GlobalProjectorLayer = 10;
    public const int GlobalProjectorLayerMask = 1 << 10;
    public const int DungeonMapLayer = 11;
    public const int DungeonMapLayerMask = 1 << 11;
    public const int RoomCollider = 12;
    public const int RoomColliderMask = 1 << 12;
 }
